# Generated by Django 4.2.7 on 2026-05-13 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ready', 'Ready for Issue'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20)),
                ('expected_issue_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField()),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['queue_position'],
            },
        ),
        migrations.RenameField(
            model_name='gadget',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.AddField(
            model_name='gadget',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gadget',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gadget',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='waitingqueue',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queues', to='gadgets.gadget'),
        ),
        migrations.AddField(
            model_name='waitingqueue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='gadgets.gadget'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gadgets.request'),
        ),
        migrations.AlterUniqueTogether(
            name='waitingqueue',
            unique_together={('student', 'gadget')},
        ),
    ]
