# Generated by Django 4.2.7 on 2026-05-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0004_queue_system_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('ready', 'Ready for Pickup'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='WaitingQueue',
        ),
    ]
